### ISSUE TITLE
"Run on startup" option is hidden when scaling is over 100%

### ISSUE THREAD

**Issue by d-anez3** [seerge/g14-helper#11]
100% scaling:
![100% scaling](https://user-images.githubusercontent.com/113142829/220238327-c39ade4c-e73d-4b1e-981a-c23fa71fd73a.jpg)

125% scaling:
![125% scaling](https://user-images.githubusercontent.com/113142829/220238349-f1e41e75-47ef-4b53-8e20-4dcc99592c7f.jpg)

This is on a 2021 G14 with the 1080p display.

**Comment by seerge** [comment]
Interesting, I tested it with scaling from 100 to 200 with every step on windows 11, and it looked ok. Could be something windows 10 specific.

I have realigned items a bit in new build, can you check it ? Thanks

https://github.com/seerge/g14-helper/releases/tag/v0.8.8

**Comment by Albert24GG** [comment]
> Interesting, I tested it with scaling from 100 to 200 with every step on windows 11, and it looked ok. Could be something windows 10 specific.
> 
> I have realigned items a bit in new build, can you check it ? Thanks
> 
> https://github.com/seerge/g14-helper/releases/tag/v0.8.8

I can confirm scaling works on windows 11 for me.

**Comment by d-anez3** [comment]
> Interesting, I tested it with scaling from 100 to 200 with every step on windows 11, and it looked ok. Could be something windows 10 specific.
> 
> I have realigned items a bit in new build, can you check it ? Thanks
> 
> https://github.com/seerge/g14-helper/releases/tag/v0.8.8

I’m also on Windows 11 but using StartAllBack for a smaller taskbar, so that might be it.

New build seems to fix it, so thank you!

**Comment by seerge** [comment]
Great!
