### ISSUE TITLE
Latest Release : Battery Charge Rate or Discharge Rate not appearing 

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g14-helper#13]
![image](https://user-images.githubusercontent.com/35734114/220445266-96632cac-5a12-487f-89c7-47e5c80fe721.png)
Hello Seerge ! 

First of all thanks for your amazing app !
In your latest release v0.9, it should be appearing the discharge and charge rate of the battery but it doesn’t 
R9 5900HS RTX3060 2021 version

Here to report the issue, it isn’t bothering me but it is worth showing this ! 

Thank you !

**Comment by seerge** [comment]
Hello Tom, you should be unplugged to see discharge (or charging to see charge). Is it the case ?

In general I use https://github.com/LibreHardwareMonitor/LibreHardwareMonitor to get sensor readings, can you install that app standalone and see if it shows your battery ?

**Comment by TomBonnot** [comment]
Ok, don’t know why but I had to unplug, replug then unplug again to get the discharge rate. Guess it didn’t get the infos or whatever. I don’t think that this bug is consistent, so everything is fine. And thank you for the foss sensor reading !
