### ISSUE TITLE
v0.9.1 Not showing CPU temps from time to time

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g14-helper#15]
I am not able to re activate the bug : I don’t know the frequency nor why it does that

![image](https://user-images.githubusercontent.com/35734114/220822676-0a4197c1-f658-4beb-9dd1-b16f5871e1b0.png)

My GHelper isn’t showing me CPU temps, but after a time it does pops, this time it doesn’t pop up. 
I let my laptop with the two others screens on and connected (running some programs), I went to eat and watch something, then it doesn’t show CPU temps anymore. 

Will edit some more infos if I detect the bug’s source !

**Comment by seerge** [comment]
Hello, just run the app as administrator (again) - it will appear

I have rewritten all core system code and now app doesn't have to be run as admin to do it's main stuff, so it runs as normal user since 0.9.1 . It's just the CPU sensor that is not available.
