### ISSUE TITLE
Anyone else getting crazy virus messages in Chrome and Windows Defender?

### ISSUE THREAD

**Issue by BuzzKnightbeer** [seerge/g14-helper#16]

**Comment by masi0** [comment]
its not a VIRUS message, its just a warning that the app has no signature/unknown signature

**Comment by seerge** [comment]
It's a standard behavior from Win Defender about unknown app. I need to buy a commercial certificate and sign app, then it should disappear. OR it will disappear if big amount of people will be using app (but this counter resets for each build unfortunately)

**Comment by BuzzKnightbeer** [comment]
That's what I'm saying. It's not just Smart Defender or whatever saying it's unsigned.
First, Chrome completely blocks it. After disabling that, Windows Defender immediately deletes the archive because it detected a virus. I don't even get to the "More info -> Run anyway" part.

On my System, it is an actual virus warning. I'll provide a screenshot as soon as I'm home again.

**Comment by seerge** [comment]
Then it's most probably a false positive from defender. Can you try latest build https://github.com/seerge/g14-helper/releases/tag/v0.9.3 if it gives you same warnings ?

**Comment by BuzzKnightbeer** [comment]
Here is a screenshot of the message in Windows Security
![Screenshot 2023-02-23 195548](https://user-images.githubusercontent.com/45749699/221088422-20128b58-1d35-4e83-9c2a-dd453b9bed26.jpg)

It doesn't come up with the latest 0.9.3 release. Neither in Chrome nor in Windows.

**Comment by seerge** [comment]
Great. Seems like was a false positive from defender before then.
