### ISSUE TITLE
Fan mode panel shows duplicated CPU fan graph and does not work

### ISSUE THREAD

**Issue by partaloski** [seerge/g14-helper#24]
**Keep in mind that I am using a G531GV - Asus ROG Strix G laptop from 2019.**

As described in the title of this issue, fan mode shows duplicated CPU fan graph and does not work.

![image](https://user-images.githubusercontent.com/24813790/221010027-5e021b16-03fd-4399-95c1-f2dbd655f56f.png)

I can still use the rest of the app good enough.

**Comment by seerge** [comment]
But thanks for noticing that label on second chart was also saying CPU instead of GPU -> it's fixed :)
