### ISSUE TITLE
[Bug] Display refresh rate control only works on "main" display, forces wrong refresh rate

### ISSUE THREAD

**Issue by flemesre** [seerge/g14-helper#3]
With an external monitor plugged in, the Laptop Screen refresh rate toggle will change the refresh rate of the external monitor instead of the laptop's internal monitor as long as the external monitor is selected as the "main" display. Not a big problem since most people will unplug a display before the charger, but it doesn't apply the 60Hz refresh rate to the laptop screen if it's already been applied to the external monitor, so it might be something to watch out for.

The slightly more broken part applies to any Zephyrus G14/G15 that doesn't have a 120Hz screen. Using the "120Hz + OD" setting doesn't restore the native high refresh rate, it just tries to apply 120Hz to the "main" display. If an external screen is plugged in before this is pressed, it will try to force 120Hz on the external screen, as mentioned above. However, my G15 2021 has a 165Hz/60Hz only screen - it can't do 120Hz, so the toggle does nothing and it stays at 60Hz. It might be better to have this toggle back to high refresh rate be user-configurable, so that it can be made to work with other Zephyrus models (probably easier than auto-detecting the correct rates).

**Comment by seerge** [comment]
I'm aware about it, will try to fix in next releases. In previous (PS1) version I was just disabling menu when saw that laptop display is not main.

**Comment by seerge** [comment]
In latest release I have tried to address both issues , let me know if it works for you
https://github.com/seerge/g14-helper/releases/tag/v0.8

**Comment by flemesre** [comment]
Works great, thanks! Fixes both issues.
