### ISSUE TITLE
Crash on TUF A15(FA507RM)

### ISSUE THREAD

**Issue by sklynic** [seerge/g14-helper#5]
Got crash on my win10pro with .NET installed. Log is below.
`Application: GHelper.exe
CoreCLR Version: 6.0.1423.7309
.NET Version: 6.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: GeneralFault 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
   at ASUSWmi.WMICall(String MethodName, Int32 Device_Id, Int32 Control_status)
   at ASUSWmi.DeviceSet(Int32 Device_Id, Int32 Control_status)
   at GHelper.SettingsForm.SetPerformanceMode(Int32 PerformanceMode)
   at GHelper.Program.Main()
`
Is there something (maybe software) missing?

**Comment by seerge** [comment]
Hello, yes! It crashed at trying to set Performance mode on your laptop. Does TUF have performance modes in armory ? If no, i can just try to disable that section on laptops that otherwise would crash there

**Comment by seerge** [comment]
I tried to suppress this crash, can you check if it runs now 
https://github.com/seerge/g14-helper/releases/tag/v0.8.4 ?

Performance modes probably won't work for your model tho

**Comment by sklynic** [comment]
Thx for quick response and give me a sec to try out.
Actually I tried this project on a MODIFIED Windows11 and it don't work, so I think it's a OS problem and installed Windows10 and get the log above.
The ArmouryCrateControlInterface and AsusSystemControlInterface Driver currently running is installed by windows update. I did't use the packages provied by asus since they pulled the win10 version driver for this laptop (this model is shipped out factory with win11 pre-installed)
I just installed ArmouryCrate and there does have a "Performance Mode". Screenshot is below.
![Capture](https://user-images.githubusercontent.com/39230198/219944555-d9e6fd6e-03e8-41f1-b533-fff63cea5880.PNG)

**Comment by sklynic** [comment]
In my opinion, something must wrong, it seems every setting leads to crash (maybe there's a different asus WMI interface?)
this time it's battery charge threshold
`Application: GHelper.exe
CoreCLR Version: 7.0.323.6910
.NET Version: 7.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: Generic failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
   at ASUSWmi.WMICall(String MethodName, Int32 Device_Id, Int32 Control_status)
   at ASUSWmi.DeviceSet(Int32 Device_Id, Int32 Control_status)
   at GHelper.SettingsForm.SetBatteryChargeLimit(Int32 limit)
   at GHelper.Program.Main()
`

**Comment by seerge** [comment]
Strange. Can you try following commands from elevated powershell prompt ? 

Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00120075; Control_status=0}

Control_status could be 0 -Balanced, 1 - Turbo, 2 - Silent

This is same as app is doing, calling that WMI method

NOTE: it won't update profile in armory! :) but you will probably hear fans turning ON at turbo, and OFF at silent + notice different PPT limits ..

**Comment by seerge** [comment]
> In my opinion, something must wrong, it seems every setting leads to crash (maybe there's a different asus WMI interface?) 

Yes, looks like you don't have it by some reason ....

Can you do `Get-CimClass -namespace root/WMI | Where-Object CimClassName -Match ".*ASUS.*"` in elevated powershell ?

**Comment by sklynic** [comment]
Tested and result is below.
What does "same environment" exactly mean, the asus driver or other related settings? (I haven't reboot after installed ArmouryCrate)
![Screenshot (1)](https://user-images.githubusercontent.com/39230198/219945546-fa0dcdb1-59c9-4333-9808-8b151c14168d.png)

**Comment by seerge** [comment]
I see, so you actually have AsusAtkWmi_WMNB .. but it doesn't recognize the same device code as G14/15 use. Nice asus! :)

Here is a cheatsheet for you https://elixir.bootlin.com/linux/latest/source/include/linux/platform_data/x86/asus-wmi.h

You can try different ones, mb ? 
`ASUS_WMI_DEVID_THERMAL_CTRL	0x00110011`

P.S. Same environment = i.e. same windows where armory works

**Comment by sklynic** [comment]
Thx for providing this sheet and some value returned, but I had better use ArmouryCrate/myASUS for another while until more incidents are reported here :-) (fonts changed because I changed language, another weird windows thing)
![a](https://user-images.githubusercontent.com/39230198/219948716-fc10306e-db24-4213-a1ab-8ff0b46578a8.PNG)

**Comment by seerge** [comment]
Hey, I have rewritten whole "system" / wmi code, and don't use that WMI calls anymore in latest build (0.9.1), can you check if it's still not working for you? or is it better?

**Comment by sklynic** [comment]
Sorry I forgot to check my email earlier... Just tried v0.9.3 and enerything works fine! Thanks a lot and I think I can close this issue now.

**Comment by sklynic** [comment]
Glad to get pre-release v0.29 but keyboard backlit sitll don't work...

But the project asusctl does work on linux (I mean the kbd Aura mode feature), maybe we can find some reference from there? Is there any way I can locate the correct device_id so I can help with this?

(I didn't find any issues or discussions dedicated for TUF's kbd backlit so I just comment here:)

**Comment by seerge** [comment]
Someone have created an issue for that https://github.com/seerge/g-helper/issues/88 but problem still stands. I can only be adding support if it's very similar to G14 (otherwise i simply can't test)

at  https://github.com/flukejones/asusctl/blob/main/rog-aura/src/builtin_modes.rs i see only one implementation (this is the one i used for G14)
