### ISSUE TITLE
Crash on Zephyrus G15 GA503RM

### ISSUE THREAD

**Issue by bootlegsushi** [seerge/g14-helper#6]
GHelper v0.8.5
> Application: GHelper.exe
> CoreCLR Version: 7.0.323.6910
> .NET Version: 7.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Management.ManagementException: Generic failure 
>    at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
>    at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
>    at ASUSWmi.WMICall(String MethodName, Int32 Device_Id, Int32 Control_status)
>    at ASUSWmi.DeviceSet(Int32 Device_Id, Int32 Control_status)
>    at GHelper.SettingsForm.SetBatteryChargeLimit(Int32 limit)
>    at GHelper.Program.Main()

**Comment by seerge** [comment]
Hello, can you try to run in elevated powershell following command 
` Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00120057 ; Control_status=80}`

It could be that your laptop doesn't support Battery Charge limits (there where it crashed)

**Comment by bootlegsushi** [comment]
![image](https://user-images.githubusercontent.com/111393006/219974282-6180aa8f-301c-4043-b3e4-084d640771e4.png)
![image](https://user-images.githubusercontent.com/111393006/219974360-5951ef8e-b003-471a-a7b4-fb3c5a191a99.png)

**Comment by seerge** [comment]
Ok, interesting :) seems like on G15 it's some other device code that is responsible for battery charge limits ... 
I have suppressed this crash, let me know if app runs for you. But battery charge limit won't work here
https://github.com/seerge/g14-helper/releases/tag/v0.8.6

**Comment by seerge** [comment]
If you will figure out which one (instead of 0x00120057) - let me know. I'll implement it

**Comment by bootlegsushi** [comment]
With v0.8.6 the program no longer crashes but at launch,  it throws up this error:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Management.ManagementException: Generic failure 
>    at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
>    at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
>    at ASUSWmi.WMICall(String MethodName, Int32 Device_Id, Int32 Control_status)
>    at ASUSWmi.DeviceGet(Int32 Device_Id)
>    at GHelper.SettingsForm.InitScreen()
>    at GHelper.SettingsForm.SettingsForm_VisibleChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
>    at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> System.Private.CoreLib
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Private.CoreLib.dll
> ----------------------------------------
> GHelper
>     Assembly Version: 1.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Runtime.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.7201
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/System.Windows.Forms.dll
> ----------------------------------------
> System.ComponentModel.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.ComponentModel.Primitives.dll
> ----------------------------------------
> System.Windows.Forms.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.7201
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/System.Windows.Forms.Primitives.dll
> ----------------------------------------
> System.Drawing.Common
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/System.Drawing.Common.dll
> ----------------------------------------
> System.Drawing.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Drawing.Primitives.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 4.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.InteropServices
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Runtime.InteropServices.dll
> ----------------------------------------
> System.Collections.Specialized
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Collections.Specialized.dll
> ----------------------------------------
> System.Diagnostics.TraceSource
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Diagnostics.TraceSource.dll
> ----------------------------------------
> System.Collections
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Collections.dll
> ----------------------------------------
> System.Threading
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Threading.dll
> ----------------------------------------
> System.Resources.Extensions
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/System.Resources.Extensions.dll
> ----------------------------------------
> System.Memory
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Memory.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.7201
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/System.Drawing.dll
> ----------------------------------------
> Microsoft.Win32.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/Microsoft.Win32.Primitives.dll
> ----------------------------------------
> System.Text.Json
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Text.Json.dll
> ----------------------------------------
> System.Collections.Concurrent
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Collections.Concurrent.dll
> ----------------------------------------
> System.Private.Uri
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Private.Uri.dll
> ----------------------------------------
> System.Text.Encodings.Web
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Text.Encodings.Web.dll
> ----------------------------------------
> System.Reflection.Emit.Lightweight
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Reflection.Emit.Lightweight.dll
> ----------------------------------------
> System.Reflection.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Reflection.Primitives.dll
> ----------------------------------------
> System.Reflection.Emit.ILGeneration
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Reflection.Emit.ILGeneration.dll
> ----------------------------------------
> System.Text.Encoding.Extensions
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Text.Encoding.Extensions.dll
> ----------------------------------------
> System.Numerics.Vectors
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Numerics.Vectors.dll
> ----------------------------------------
> System.Threading.Thread
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Threading.Thread.dll
> ----------------------------------------
> Microsoft.Win32.Registry
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/Microsoft.Win32.Registry.dll
> ----------------------------------------
> System.ComponentModel.EventBasedAsync
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.ComponentModel.EventBasedAsync.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 7.0.323.7201
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/Accessibility.dll
> ----------------------------------------
> System.ComponentModel.TypeConverter
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.ComponentModel.TypeConverter.dll
> ----------------------------------------
> System.ObjectModel
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.ObjectModel.dll
> ----------------------------------------
> System.ComponentModel
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.ComponentModel.dll
> ----------------------------------------
> Microsoft.Win32.SystemEvents
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.3/Microsoft.Win32.SystemEvents.dll
> ----------------------------------------
> System.Runtime.Intrinsics
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Runtime.Intrinsics.dll
> ----------------------------------------
> Microsoft.Win32.TaskScheduler
>     Assembly Version: 2.10.1.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Linq
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Linq.dll
> ----------------------------------------
> System.Diagnostics.FileVersionInfo
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Diagnostics.FileVersionInfo.dll
> ----------------------------------------
> System.Text.RegularExpressions
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Text.RegularExpressions.dll
> ----------------------------------------
> System.Xml.ReaderWriter
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Xml.ReaderWriter.dll
> ----------------------------------------
> System.Private.Xml
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Private.Xml.dll
> ----------------------------------------
> System.Collections.NonGeneric
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Collections.NonGeneric.dll
> ----------------------------------------
> System.Runtime.Loader
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Runtime.Loader.dll
> ----------------------------------------
> System.Diagnostics.StackTrace
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Diagnostics.StackTrace.dll
> ----------------------------------------
> System.Reflection.Metadata
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Reflection.Metadata.dll
> ----------------------------------------
> System.Collections.Immutable
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.323.6910
>     CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.3/System.Collections.Immutable.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************

The program runs when I hit continue though.

**Comment by seerge** [comment]
That's another feature, that is not supported by WMI calls on your laptop, screen overdrive.

I have uploaded a fix (to the same release) https://github.com/seerge/g14-helper/releases/tag/v0.8.6 

Let me know if it works now

**Comment by bootlegsushi** [comment]
With that release, only the GPU mode switching and screen refresh rate change (aside from the same error thrown trying to switch to 165Hz + OD, which does switch to after hitting continue) seems to work.

**Comment by seerge** [comment]
Yeah, cause it was trying to set same overdrive again there ... i have suppressed that crash too (same old link)

**Comment by seerge** [comment]
Does G15 have screen overdrive at all ? (in armory)

**Comment by bootlegsushi** [comment]
![image](https://user-images.githubusercontent.com/111393006/219976877-78243db2-6e00-457b-9a33-0e404c4c6915.png)

**Comment by seerge** [comment]
Ok, then it's (again) some other device_id responsible for that. If you will somehow find those - let me know

**Comment by seerge** [comment]
I'm closing this, as it doesn't  seem to crash anymore, even tho that feature doesn't work on g15 for now
